### ISSUE TITLE
泰晓资讯 06月 / 第二期 / 2019 —— 资讯收集

### ISSUE THREAD

**Issue by unicornx** [tinyclub/tinylab.org#323]
[LWN.net Weekly Edition for May 30, 2019](https://lwn.net/Articles/789231/)

- [[**unicornx**]A kernel debugger in Python: drgn][1]: an LSFMM session on an interesting debugging tool.
- [[**unicornx**]Improving .deb][2]: a discussion on changes to the venerable .deb package format.
- [[**unicornx**]New system calls: pidfd_open() and close_range()][3]: proposed system calls for opening pidfds and wholesale closing of ranges of file descriptors.
- [[**unicornx**]New system calls for memory management][4]: three more system-call proposals, these for memory-management tasks.
- [[**unicornx**]Memory: the flat, the discontiguous, and the sparse][5]: a historical look at how the kernel represents physical memory.
- Our last batch of coverage from the 2019 Linux Storage, Filesystem, and Memory-Management Summit:
    - [Testing and the stable tree][6]
    - [Storage testing][7]
    - [A way to do atomic writes][8]
    - [The Linux "copy problem"][9]
    - [Shrinking filesystem caches for dying control groups][10]

[[**unicornx**]Brief items](https://lwn.net/Articles/789233/): Brief news items from throughout the community.

[1]: https://lwn.net/Articles/789641/
[2]: https://lwn.net/Articles/789449/
[3]: https://lwn.net/Articles/789023/
[4]: https://lwn.net/Articles/789153/
[5]: https://lwn.net/Articles/789304/
[6]: https://lwn.net/Articles/789225/
[7]: https://lwn.net/Articles/789538/
[8]: https://lwn.net/Articles/789600/
[9]: https://lwn.net/Articles/789623/
[10]: https://lwn.net/Articles/789640/

**Comment by unicornx** [comment]
![image](https://user-images.githubusercontent.com/2476165/59012688-ba003f00-886a-11e9-8de2-57c804d54a6a.png)

**Comment by lzufalcon** [comment]
[falcon] [Testing and the stable tree](https://lwn.net/Articles/789225/) : how to make stable-tree really stable.

Levin 一直致力于让 Linux 内核的 [Stable tree](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/) 更加的 Stable，他的两个关注方向是：”that fewer regressions are released“ 和 ”that all of the fixes get out there for users“。

第二点在 2018 年北美开源峰会上，Levin 介绍了 [Machine learning and stable kernels](https://lwn.net/Articles/764647/)，旨在自动的发现那些没有被人主动提交给 Stable release 的 patch，确保有更多的 fixes 能够同步到 Stable tree。

第一点则是如何确保这些 fixes 在人工 Review 之后有更充分的测试，这个 Topic 主要是聚焦这个问题。大家讨论到了用于 Filesystem 的 [xfstests](https://github.com/kdave/xfstests)，用于 Storage 的 [blktests](https://github.com/osandov/blktests)，用于 Memory 的 [MMTests](https://github.com/gormanm/mmtests)。另外，大家也讨论到用哪些自动化的测试框架来跑这些测试，作者希望是 [KernelCI](https://kernelci.org/)，有听众提到为什么不是 [O-Day automated testing](https://01.org/lkp/documentation/0-day-test-service)，作者回复 O-Day 是 Semi Open 的不如完全开源的 KernelCI。后面大家有讨论一个 include/exclude list 的问题，主要原因是这些测试用例跑的时间可能很长或者本身并不能在任意内核版本任意配置选项上跑，所以需要维护一个子集，还要排除一些可能导致 false-positive 的特定 Test Case，[LTP](https://linux-test-project.github.io/) 是一个很典型的例子，它有数千个测试用例，但是不能照搬直接放到产品测试中，因为它本身会带来大量的误报（发现的Bug并不影响最终产品，但是可能需要耗费大量时间解决），需要设立 include/exclude list。

Levin 最后呼吁大家把好的 Test Case 贡献到 KernelCI，以便 Stable tree 可以跑更多更好的测试，从而让 Stable tree really stable。

**Comment by lzufalcon** [comment]
[falcon] [Storage testing](https://lwn.net/Articles/789538/): how to use blktests

来自 Google 的 Ted Ts 同学最近在玩 NFS testing 和 [blktests](https://github.com/osandov/blktests)，NFS testing 主要用 [xfstests](https://github.com/kdave/xfstests)。它用 blktests 找到了一个 ext4 的衰退，当然这个问题表现是 ext4，但是实际问题可能出在 SCSI multiqueue，block layer。他已经把这个用例集成进了他自己的自动化测试平台。他发现 blktests 还有待完善，比如说要跑所有的测试依赖打开 38 个内核模块，但是 blktests 并没有说明，他正准备把相关的 setup 工作贡献进 blktests，他建议更多的kernel developer 来跑 blktests，“it makes his life easier”。

**Comment by lzufalcon** [comment]
[falcon] [A way to do atomic writes](https://lwn.net/Articles/789600/)

> Application developers hate the fact that when they update files in place, a crash can leave them with old or new data—or sometimes a combination of both. He discussed some implementation ideas that he has for atomic writes for XFS and wanted to see what the other filesystem developers thought about it.

**Comment by lzufalcon** [comment]
[falcon] [The Linux "copy problem"](https://lwn.net/Articles/789623/): it that possible to make copy faster?

> Much of the development work that has gone on in the Linux filesystem world over the last few years has been related to the performance of copying files, at least indirectly, he said. There are still pain points around copy operations, however, so he would like to see those get addressed.

French 抛出这样一个问题，是发现，虽然随着硬件性能的提升（NVMe/UFS）， cp 性能有了很大的提升，但是 Linux 下的 cp 性能表现还是有点”难堪“，软件上尤其是内核上能够配合软件做哪些工作才能有所改善呢？他做了一些数据测试：

> On the fast drive, for a 2GB copy on ext4, cp took 1.2s (1.7s on the slow), scp 1.7s (8.4s), and rsync took 4.3s (not run on the slow drive, apparently). These represent "a dramatic difference in performance" for a "really stupid" copy operation

他分析后发现可能是 cp 用了 128K I/O size，而其他的都用了 16k，其他工具，比如 [parcp](https://blogs.oracle.com/cloud-infrastructure/announcing-parallel-file-tools-for-file-storage), [parallel](https://www.gnu.org/software/parallel/), [fpart and fpsync](https://github.com/martymac/fpart), [mutil](https://github.com/pkolano/mutil) 则采用了并行的优化方法， 那么文件系统能做哪些工作呢？

* copy_file_range: 比如说目前内核中 5 个左右的文件系统支持 [copy_file_range()](http://man7.org/linux/man-pages/man2/copy_file_range.2.html)，但是 Btrfs 目前却不支持。这个函数旨在在内核中完成两个文件之间的拷贝，避免数据从用户空间和内存空间来回搬动。

*  ACLS/xattrs：目前没有一个 API 可以完整的复制整个文件以及其 meta data，所以是要提供一个用户空间的 library 还是说内核可以做点什么呢，尤其是跟 security 相关的部分。

* I/O size: 这个参数依赖于硬件，但是目前用户空间从 stat() 拿到的是 st_blksize 只是文件系统的 block size，并不是设备支持的最佳 I/O size，所以是否有必要增加一个参数到 statx()？不过对于挂了不同设备的 RAID 而言，还得 RAID controller 跟设备去打交道，获得这个数据。

* page cache:  是不是可以提供一个方式，让用户空间关闭 page cache。对于马上要访问的数据而言，page cache是有价值的，比如说拷贝了一份内核，马上要编译，但是拷贝完如果不用，这个 page cache 就是没有必要走的路径，关掉会提升不少性能。

* fiemap: fiemap 用于取代 block by block mapping，在连续 block 之上构建一个 extent，从而减少元数据的开销，即 bitmap 的开销，文件系统支持这样的特性也可以提升性能。

> French said that Linux copy performance was a bit embarrassing; OS/2 was probably better for copy performance in some ways. But he did note that the way sparse files were handled using FIEMAP in cp was great. Ts'o pointed out that FIEMAP is a great example of how the process should work. Someone identified a problem, so kernel developers added a new feature to help fix it, and now that code is in cp; that is what should be happening with any other kernel features needed for copy operations.

French 发起的这个话题引人深思，内核以及 Kernel Developer 永远不是独立的，完整交付给用户的 Linux System 还包含了其他工具，如果最后确实有体验上的问题，Kernel Developer 不能把问题简单抛给 User space developer，去做并行就好了嘛？所以，French 的工作态度很值得赞赏！

> French would like to see the filesystem developers participate in developing the tools or at least advising those developers.

不同社区共同协作，甚至在这样的峰会上主动邀请相关的 User space developer 参加或许是更好的方向。感谢社区中那些积极思考和探索 "really stupid" 的 "cp problem"。

**Comment by lzufalcon** [comment]
[falcon] [Shrinking filesystem caches for dying control groups](https://lwn.net/Articles/789640/): reparent
the accounted slabs to the parent cgroup on cgroup removal.

> Control groups are managed using a virtual filesystem; a particular group can be deleted just by removing the directory that represents it. But the truth of the matter, Gushchin said, is that while removing a control group's directory hides the group from user space, that group continues to exist in the kernel until all references to it go away. While it persists, it continues to consume resources.

> Specifically, for control groups that share the same underlying filesystem, the shrinkers are not able to reclaim memory from the VFS caches after a control group dies, at least under slight to moderate memory pressure.

Control Group 被设计用来更好地管理资源，但是它自己也面临了资源回收的问题。每个控制组在不用的时候可以从用户空间把相应的目录删掉，但是实际上，内核空间还会保留相应的资源，直到相关的资源引用计数都变为 0，而相应的资源回收需要触发 memory shrinker，但是 memory shrinker 通常有一定的条件，比如要申请的内存超过了某一个门限，如果系统还有足够的内存，那么 memory shrinker 就不会触发，这会导致会有大量的这样的 Control Group 累计，虽然每个只占用了 200KB 的空间，但是 Gushchin 发现 `I've even seen a host with more than 100Gb of memory wasted for dying cgroups`。

Gushchin 早期的方案是制造一个 memory shrinker 的 pressure，触发系统回收内存，但是引起了性能衰退，被 Revert 了。目前他提出了一个[方案](https://lwn.net/Articles/787614/)，就是把被删除的 Control Group 的 pages 挂到它的父 Control Group 上，这样它自己就可以从容离开。目前的[测试数据](https://lwn.net/ml/linux-kernel/20190423213133.3551969-1-guro%40fb.com/)来看，确实解决了问题，期望能够很快在内核主线上看到，这个对于云服务主机可能会很有帮助。

**Comment by lzufalcon** [comment]
May 23 of LWN, left LSFMM parts:

[falcon] [Supporting the UFS turbo-write mode](https://lwn.net/Articles/788721/): Faster for some scenes？

> A new version of the UFS specification is being written and turbo-write is expected to be part of it. The idea behind turbo-write is to use an SLC buffer to provide faster writes, with the contents being shifted to the slower TLC as needed.

关注手机的用户可能能深刻体会到，这几年发展下来，手机是越来越快，这得益于手机的处理器频率的提升（更好设计和制作工艺），当然也得益于更快的存储技术，而 UFS 就是这里头的一个大功臣。早期 eMMC 通过并行不断提升读写速度，但是 UFS 通过更高速的串行双工通信解决了 eMMC 发展遇到的瓶颈，速度得到了数倍的提升。

当然，大家可能还有一个深刻的感受就是随着时间的推移，手机越来越慢，原因是另外一个背景，也就是在 eMMC 和 UFS 这两个通信标准的背后，都是存储芯片，而存储芯片也经历了三个重要的发展阶段，即 SLC, MLC 和 TLC，演进是更大的存储空间，更低的成本，但是却迎来了更低的擦写寿命（写到一定程度存在漏电）和更慢的读写速度。这个演进过程是通过引入不同电为的电荷增加单个 CELL 的表达的位数，随着位数的增多，SLC single-level-cell, MLC 2bits-per-cell, TLC 3bits-per-cell，所以操作复杂度和寿命下降就比较容易理解，MLC 和 TLC 的寿命只有 SLC 的 1/10, 1/20，TLC 单个存储单元的擦写次数只有 500 次左右（相当于一个 64G 的 TLC 芯片可以写入 32000 G 新内容，也没有想象的少哈），而 MLC 在 1万次左右，SLC 则能到 10 万次。但是由于成本大幅下降，所以市面上现在 TLC, MLC 的比较多，或者有跟 SLC 混合的产品。

这里的 "turbo mode" 就是用来管理 SLC 和 TLC/MLC 混合的产品，"turbo mode" 用于直接写入 SLC，但是 SLC 容量比较有限，一直开着这个模式会写满，很快就慢了，所以，一方面要管理什么情况下做 "turbo mode"，另外一个是什么时候在后台把内容从 SLC 搬到 TLC，确保需要的时候，"turbo mode" 可以工作。

**Comment by lzufalcon** [comment]
May 23 of LWN, left LSFMM parts:

[falcon] [Filesystems for zoned block devices](https://lwn.net/Articles/788851/): new filesystem support  for SMR storage

> zoned block devices  have multiple zones with different characteristics; usually there are zones that can only be written in sequential order as well as conventional zones that can be written in random order. The genesis of zoned block devices is shingled magnetic recording (SMR) devices, which were created to increase the capacity of hard disks, but at the cost of some flexibility.

[SMR](https://en.wikipedia.org/wiki/Shingled_magnetic_recording) 存储通过缩小磁盘间距离甚至允许磁轨重叠从而提升存储密度，但是会牺牲写入操作的灵活性。这里讨论了如果一块磁盘，一部分用了 SMR（仅支持顺序写），一部分是传统的磁盘，需要什么样的文件系统。目前社区正在添加支持的文件系统有 F2FS，Brtfs，还有一个是新开发的 ZoneFS。

> ZoneFS is a new filesystem that exposes zoned block devices to users in the simplest possible way, Le Moal said. It exports each zone as a file under the mountpoint in two directories: /conventional for random-access zones or /sequential for sequential-only zones. Under those directories, the zones will be files that use the zone number as the file name.

三者的状态都不完善，还在不断开发中。

**Comment by lzufalcon** [comment]
May 23 of LWN, left LSFMM parts:

[falcon] [Filesystems and crash resistance](https://lwn.net/Articles/788938/): another topic about ”atomic write“

> Currently, there are applications that create and populate a temporary file, set the attributes desired, then rename it, Goldstein said. The developers think that the file is written persistently to the filesystem, which is not true, but mostly works. The official answer is that you must use fsync(), but it is a "terrible answer" because it has impacts all over the system.

又在讨论 Application Developers 渴望确保数据真正回写到磁盘的需求，只是讨论到最后也没有结论。另外一篇讨论在 [The Linux "copy problem"](https://lwn.net/Articles/789623/)，反而有一些实质的讨论成果。

> There are two types of barriers that he is talking about. The first would be used by overlayfs; it sets extended attributes (xattrs) on a file, then renames it. Overlayfs expects that, if the rename is observed, then the metadata has been written persistently. The other barrier is for data to be persistently written, which can be done today using the FIEMAP ioctl() command (with the FIEMAP_FLAG_SYNC flag), at least for XFS and ext4, he asserted.

实际上有其他人补充，即使是 XFS 和 ext4，FIEMAP 在 Sparse files 上也不能保证原子写入。

**Comment by lzufalcon** [comment]
May 23 of LWN, left LSFMM parts:

[falcon] [Asynchronous fsync()](https://lwn.net/Articles/789024/): fsync2() or io_uring based version of fsync()?

> The idea of an asynchronous version of fsync() is kind of counter-intuitive, Wheeler said. But there are use cases in large-scale data migration. If you are copying a batch of thousands of files from one server to another, you need a way to know that those files are now durable, but don't need to know that they were done in any particular order. You could find out that the data had arrived before destroying the source copies.

Wheeler 抛出来一个这样的主题是希望有这么一个 API，能够批处理一批文件，但是不要依赖特别的 order。有人建议用 [io_uring](https://lwn.net/Articles/776703/)：

> The io_uring interface allows arbitrary operations to be done in a kernel worker thread and, when they complete, notifies user space.

但是 Wheeler 看上去并不是希望这样，所以 Ts'o 提出了 fsync2():

> fsync2() that takes an array of file descriptors and returns when they have all been synced. If the filesystem has support for fsync2(), it can do batching on the operations. It would be easier for application developers to call a function with an array of file descriptors rather than jumping through the hoops needed to set up an io_uring, he said.

与其在内核这么复杂的操作，那再用户态实现一个基于 io_uring 的 library 不也可以吗？！

**Comment by lzufalcon** [comment]
May 23 of LWN, left LSFMM parts:

[falcon] [Lazy file reflink](https://lwn.net/Articles/789038/):  VFS-level snapshots

> Amir Goldstein has a use case for a feature that could be called a "lazy file reflink", he said, though it might also be described as "VFS-level snapshots".

**Comment by unicornx** [comment]
[New system calls: pidfd_open() and close_range()][https://lwn.net/Articles/789023/]: proposed system calls for opening pidfds and wholesale closing of ranges of file descriptors.

参考 [Rethinking race-free process signaling](https://lwn.net/Articles/784831/)
5.1 kernel introduced a new system call `pidfd_send_signal()`. pidfd 概念的引入是为了解决如果直接采用进程号发送信号有可能发送给错误的进程对象，因为进程号可能循环使用。
late March, Christian Brauner posted a patch set adding another new system call: `pidfd_open()` 除此之外还引入一个ioctl的使用。linus认可pidfd_open的引入但反对ioctrl

pidfd_open 的做法会引入竞争，而真正会消除竞争的做法是通过clone

另一个参考，时间更早 [Toward race-free process signaling](https://lwn.net/Articles/773459/)
有关信号的设计存在许多缺陷，历史上的改进很多，譬如signalfd()
但最近内核社区开始关注的一个问题是有关发送信号中使用的进程号存在竞争问题。
Signal-related APIs identify processes by PID. The disadvantage of this method is that, in the lifetime of a system, the same PID is reused as processes are created and terminated. 
这篇文章介绍了Brauner主导的补丁的由来。It proposes to solve the signal delivery issue by using file descriptors to identify processes; these descriptors would be obtained by opening a process's /proc directory.

**Comment by unicornx** [comment]
[A kernel debugger in Python: drgn](https://lwn.net/Articles/789641/)

来自 Facebook 的 Omar Sandoval 在 2019 LSFMM 峰会上给大家介绍了他开发的一款内核调试器 [drgn](https://github.com/osandov/drgn)。利用该调试器，开发人员可以使用 python 脚本，在运行期访问内核的数据结构，譬如，检查 root 文件系统的 superblock 信息以及遍历该 superblock 缓存的的所有 inode 信息。

**Comment by unicornx** [comment]
[Improving .deb](https://lwn.net/Articles/789449/)

Debian 及其派生系列（如 Ubuntu）的一些共同特点是使用 `.deb` 作为分发打包的格式。有关该打包格式的最后一次重大改版发生在 1995 年，此后一直未有什么变化，具体 `.deb` 的格式可以参考 deb(5) 手册的描述。然而，最近在 debian-devel 邮件列表中，由 Adam Borowski 发起，讨论了对该格式进行改进的可能性。
Borowski 所提出的改进并不复杂，很容易实现。包括：
- 采用 zstd 代替 xz 对内容进行压缩，主要考虑是可以加快解压的速度
- 重新使用老的（1995 年之前）的打包格式，目的是为了避免现在格式中对打包数据长度的限制。
- 使用 tar 代替 ar 来对数据进行打包。
由于众说纷纭，就改变 `.deb` 的打包方式上，社区目前并没有达成一致的意见。

**Comment by unicornx** [comment]
[New system calls for memory management](https://lwn.net/Articles/789153/)

最近社区提出了几个新的系统调用，希望能够在近期版本中被添加到内核中。其中一些特别关注内存管理任务。继续阅读，
一个是 Kirill Tkhai 提出的 `process_vm_mmap()`，可以实现将一个进程的 VMA 克隆到另一个进程中（这期间会涉及对相应页表（page table）的克隆）。该系统调用可以提供类似于采用两个已存在的系统调用 `process_vm_writev()` 和 `process_vm_readv()` 可以实现的功能，但效率会更高。



以及两个新的API，用于建议内核在不同进程中使用内存。

**Comment by unicornx** [comment]
[Memory: the flat, the discontiguous, and the sparse](https://lwn.net/Articles/789304/)

这是一篇综述一般的介绍，不适合作为资讯新闻。

**Comment by unicornx** [comment]
[Brief items](https://lwn.net/Articles/789233/)

**Comment by lzufalcon** [comment]
其他资讯速递

* [Qemu 发布 v4.0.0](https://www.qemu.org/2019/04/24/qemu-4-0-0/), add [micro:bit](http://microbit.org/) support
* [U-Boot 发布 U-Boot v2019.07-rc4](https://lists.denx.de/pipermail/u-boot/2019-June/372312.html)
* [Buildroot 发布 2019.05](http://lists.busybox.net/pipermail/buildroot/2019-June/251548.html)，Linux: Default to 5.1.x series
* [Busybox 发布 BusyBox 1.31.0](https://busybox.net/news.html)
* [LLVM 发布 8.0.1-rc2](http://llvm.org/)
* [GCC 发布 9.1](https://gcc.gnu.org/gcc-9/)
* [Linux RT 发布 v5.0.19-rt11](https://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-rt-devel.git/log/?h=linux-5.0.y-rt)
* [Rust 发布 1.35.0](https://blog.rust-lang.org/2019/05/23/Rust-1.35.0.html)

**Comment by lzufalcon** [comment]
已整理完毕，即将发布。
