### ISSUE TITLE
move pic to local

### ISSUE THREAD

**Issue by unicornx** [tinyclub/tinylab.org#375]
资讯中引用的图片来自外网链接，制作 gitbook 导致hang。
把外网链接改成本地图片，注意压缩图片大小，避免repo size过大。

**Comment by lzufalcon** [comment]
外网链接可能要备注一下来源。

**Comment by unicornx** [comment]
> 外网链接可能要备注一下来源。

![image](https://user-images.githubusercontent.com/2476165/62846556-aa3a2680-bd03-11e9-92a6-04592df839e6.png)

我现在在发布的时候就是这样备注的，你看还行啊？

**Comment by unicornx** [comment]
目前暂无修改计划，已经在资讯中尽量避免使用外链图片，制作合集时也会过滤掉，所以暂时没有紧迫的需求做本修改，先关闭。
