### ISSUE TITLE
tools/draft doesn't work well

### ISSUE THREAD

**Issue by unicornx** [tinyclub/tinylab.org#394]
[console.log](https://github.com/tinyclub/tinylab.org/files/3549389/console.log)
refer to the attached console.log
two issues found
1) totally 26 files (1 ~ 26 files listed, but the tools indicated select(0~28)?
2) directly press return and doesnot return as promised before, but selected a wrong file to be modified (read log file for details)

**Comment by lzufalcon** [comment]
@unicornx 已经解决了，先关闭哈。
